/**
 * Starlake.AI JSQLTranspiler is a SQL to DuckDB Transpiler.
 * Copyright (C) 2025 Starlake.AI (hayssam.saleh@starlake.ai)
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ai.starlake.transpiler.schema;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Savepoint;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.*;

/** Live DB2/MySQL regressions using isolated tables in the configured schema/database. */
class Db2MySqlMetaDataTest {
  @ParameterizedTest(name = "DB2, autoCommit={0}")
  @CsvSource({"true", "false"})
  void db2Catalog(boolean autoCommit) throws Exception {
    catalogKeysAndTransactionPreservation("db2", autoCommit);
  }

  @ParameterizedTest(name = "MySQL, autoCommit={0}, databaseTerm={1}")
  @CsvSource({"true,CATALOG", "false,CATALOG", "true,SCHEMA", "false,SCHEMA"})
  void mysqlCatalog(boolean autoCommit, String databaseTerm) throws Exception {
    catalogKeysAndTransactionPreservation("mysql", autoCommit, databaseTerm);
  }

  @ParameterizedTest(name = "MariaDB profile on MySQL, autoCommit={0}")
  @CsvSource({"true", "false"})
  void mariaDbProfileCatalog(boolean autoCommit) throws Exception {
    catalogKeysAndTransactionPreservation("mariadb-profile", autoCommit);
  }

  private Connection mariaDbProfile(Connection conn) {
    DatabaseMetaData metadata =
        (DatabaseMetaData) Proxy.newProxyInstance(getClass().getClassLoader(),
            new Class<?>[] {DatabaseMetaData.class},
            (proxy, method, args) -> "getDatabaseProductName".equals(method.getName()) ? "MariaDB"
                : invoke(conn.getMetaData(), method, args));
    return (Connection) Proxy.newProxyInstance(getClass().getClassLoader(),
        new Class<?>[] {Connection.class},
        (proxy, method, args) -> "getMetaData".equals(method.getName()) ? metadata
            : invoke(conn, method, args));
  }

  private void catalogKeysAndTransactionPreservation(String database, boolean autoCommit)
      throws Exception {
    catalogKeysAndTransactionPreservation(database, autoCommit, "CATALOG");
  }

  private void catalogKeysAndTransactionPreservation(String database, boolean autoCommit,
      String databaseTerm) throws Exception {
    boolean mariaDbProfile = "mariadb-profile".equals(database);
    java.util.Properties overrides = new java.util.Properties();
    if (!"db2".equals(database)) {
      overrides.setProperty("databaseTerm", databaseTerm);
    }
    try (Connection physical =
        LiveDatabaseProperties.connect(mariaDbProfile ? "mysql" : database, overrides)) {
      Connection conn = mariaDbProfile ? mariaDbProfile(physical) : physical;
      boolean db2 = "db2".equals(database);
      String prefix = "JT"
          + UUID.randomUUID().toString().replace("-", "").substring(0, 12).toUpperCase(Locale.ROOT);
      String schema = db2 ? conn.getSchema().stripTrailing()
          : "SCHEMA".equals(databaseTerm) ? conn.getSchema() : conn.getCatalog();
      List<String> created = new ArrayList<>();
      String parent = schema + "." + prefix + "_P";
      String child = schema + "." + prefix + "_C";
      String composite = schema + "." + prefix + "_F";
      String noKey = schema + "." + prefix + "_N";
      conn.setAutoCommit(true);
      try {
        create(conn, created, parent, "ID INT NOT NULL "
            + (db2 ? "GENERATED BY DEFAULT AS IDENTITY" : "AUTO_INCREMENT") + " PRIMARY KEY");
        create(conn, created, child,
            "A INT NOT NULL, B INT NOT NULL, P INT, LABEL VARCHAR(40) DEFAULT 'pending' "
                + (db2 ? "" : "COMMENT 'Live label fixture'") + ", "
                + (db2 ? "COMPUTED INT GENERATED ALWAYS AS (A+B)"
                    : "COMPUTED INT GENERATED ALWAYS AS (A+B) STORED")
                + ", PRIMARY KEY(A,B), FOREIGN KEY(P) REFERENCES " + parent
                + "(ID) ON DELETE CASCADE");
        create(conn, created, composite,
            "X INT, Y INT, FOREIGN KEY(X,Y) REFERENCES " + child + "(A,B)");
        create(conn, created, noKey, "ID INT");
        execute(conn, "CREATE INDEX " + prefix + "_IX ON " + child + "(P)");
        if (db2) {
          execute(conn, "COMMENT ON TABLE " + child + " IS 'Live child fixture'");
          execute(conn, "COMMENT ON COLUMN " + child + ".LABEL IS 'Live label fixture'");
        } else {
          execute(conn, "ALTER TABLE " + child + " COMMENT = 'Live child fixture'");
        }
        conn.setAutoCommit(autoCommit);
        execute(conn, "INSERT INTO " + noKey + " VALUES (42)");
        Savepoint caller = autoCommit ? null : conn.setSavepoint();
        AtomicInteger calls = new AtomicInteger();
        Connection measured = measure(conn, calls);
        String currentCatalog = conn.getCatalog();
        String currentSchema = conn.getSchema();
        JdbcMetaData metadata = new JdbcMetaData(measured, List.of(schema.toLowerCase(Locale.ROOT)),
            JdbcMetaDataOptions.defaults());
        int initialCalls = calls.get();
        JdbcTable p = table(metadata, schema, prefix + "_P");
        JdbcTable c = table(metadata, schema, prefix + "_C");
        JdbcTable f = table(metadata, schema, prefix + "_F");
        assertEquals(List.of("ID"), p.primaryKey.getColumnNames());
        assertEquals("YES", p.columns.get("ID").isAutomaticIncrement);
        assertEquals(List.of("A", "B"), c.primaryKey.getColumnNames());
        assertEquals(1, c.foreignKeys.size());
        assertEquals(DatabaseMetaData.importedKeyCascade,
            c.foreignKeys.get(0).deleteRule.intValue());
        assertEquals(1, f.foreignKeys.size());
        assertArrayEquals(new String[] {"X", "A"}, f.foreignKeys.get(0).columns.get(0));
        assertArrayEquals(new String[] {"Y", "B"}, f.foreignKeys.get(0).columns.get(1));
        assertNull(table(metadata, schema, prefix + "_N").primaryKey);
        assertEquals("Live child fixture", c.remarks);
        assertEquals("Live label fixture", c.columns.get("LABEL").remarks);
        assertTrue(c.columns.get("LABEL").columnDefinition.contains("pending"));
        assertEquals("YES", c.columns.get("COMPUTED").isGeneratedColumn);
        assertEquals(4, c.columns.get("LABEL").ordinalPosition);
        for (JdbcTable t : List.of(p, c, f)) {
          assertFalse(t.columns.isEmpty());
          for (JdbcColumn column : t.columns.values()) {
            assertEquals(t.tableCatalog, column.tableCatalog);
            assertEquals(t.tableSchema, column.tableSchema);
          }
        }
        if (db2) {
          assertEquals("", metadata.getCurrentCatalogName());
        }
        assertNotNull(new ai.starlake.transpiler.JSQLColumResolver(metadata).getLineage(
            ai.starlake.transpiler.schema.treebuilder.JSONObjectTreeBuilder.class,
            "select x.ID from " + prefix + "_P x"));
        if (!db2) {
          for (String tableName : List.of(schema + "." + prefix + "_P",
              "`" + schema + "`.`" + prefix + "_P`")) {
            org.json.JSONObject column = new ai.starlake.transpiler.JSQLColumResolver(metadata)
                .getLineage(ai.starlake.transpiler.schema.treebuilder.JSONObjectTreeBuilder.class,
                    "select x.ID from " + tableName + " x")
                .getJSONArray("columnSet").getJSONObject(0);
            assertEquals(schema + "." + prefix + "_P", column.getString("table"));
            assertFalse(column.optString("scope").contains(".."));
            JdbcMetaData restored = JdbcJSONSerializer
                .fromJson(new java.io.StringReader(JdbcJSONSerializer.toJson(metadata).toString()));
            org.json.JSONObject restoredColumn =
                new ai.starlake.transpiler.JSQLColumResolver(restored)
                    .getLineage(
                        ai.starlake.transpiler.schema.treebuilder.JSONObjectTreeBuilder.class,
                        "select x.ID from " + tableName + " x")
                    .getJSONArray("columnSet").getJSONObject(0);
            assertEquals(schema + "." + prefix + "_P", restoredColumn.getString("table"));
            assertEquals(schema + "." + prefix + "_P.ID", restoredColumn.getString("scope"));
          }
        }
        String json = JdbcJSONSerializer.toJson(metadata).toString();
        assertEquals(json, JdbcJSONSerializer
            .toJson(JdbcJSONSerializer.fromJson(new java.io.StringReader(json))).toString());
        JdbcMetaData indexed = new JdbcMetaData(conn, List.of(schema),
            JdbcMetaDataOptions.defaults().setIndices(true));
        assertTrue(table(indexed, schema, prefix + "_C").indices.values().stream()
            .anyMatch(index -> (prefix + "_IX").equalsIgnoreCase(index.indexName)));
        assertEquals(currentCatalog, conn.getCatalog());
        assertEquals(currentSchema, conn.getSchema());
        assertEquals(autoCommit, conn.getAutoCommit());
        if (!autoCommit) {
          conn.rollback(caller);
        }
        assertMarker(conn, noKey);
        // End the transaction before MySQL committing DDL; test a fresh transaction afterward.
        if (!autoCommit) {
          conn.rollback();
        }
        conn.setAutoCommit(true);
        for (int i = 0; i < 20; i++) {
          create(conn, created, schema + "." + prefix + "_M" + i,
              "ID INT NOT NULL PRIMARY KEY, P INT, FOREIGN KEY(P) REFERENCES " + parent + "(ID)");
        }
        conn.setAutoCommit(autoCommit);
        calls.set(0);
        JdbcMetaData large =
            new JdbcMetaData(measured, List.of(schema), JdbcMetaDataOptions.defaults());
        if (!db2) {
          assertEquals(initialCalls, calls.get(),
              "Bulk metadata query count must not grow with tables");
        } else {
          assertTrue(calls.get() > initialCalls,
              "DB2 uses the supported per-table JDBC key fallback");
        }
        for (int i = 0; i < 20; i++) {
          JdbcTable t = table(large, schema, prefix + "_M" + i);
          assertNotNull(t.primaryKey);
          assertEquals(1, t.foreignKeys.size());
        }
        assertTrue(
            new JdbcMetaData(conn, List.of(prefix + "_MISSING"), JdbcMetaDataOptions.defaults())
                .getCatalogsList().stream().flatMap(catalog -> catalog.schemas.values().stream())
                .allMatch(s -> s.tables.isEmpty()));
        System.out.println(database + " " + conn.getMetaData().getDatabaseProductVersion()
            + ", driver " + conn.getMetaData().getDriverVersion() + ": " + initialCalls
            + " metadata calls for 4 tables, " + calls.get() + " for 24; autoCommit=" + autoCommit);
      } finally {
        if (!conn.getAutoCommit()) {
          conn.rollback();
          conn.setAutoCommit(true);
        }
        for (int i = created.size() - 1; i >= 0; i--) {
          execute(conn, "DROP TABLE " + created.get(i));
        }
      }
    }
  }

  private static void create(Connection conn, List<String> created, String table, String fields)
      throws Exception {
    execute(conn, "CREATE TABLE " + table + "(" + fields + ")");
    created.add(table);
  }

  private static void execute(Connection conn, String sql) throws Exception {
    try (Statement statement = conn.createStatement()) {
      statement.execute(sql);
    }
  }

  private static void assertMarker(Connection conn, String table) throws Exception {
    try (Statement statement = conn.createStatement();
        ResultSet rs = statement.executeQuery("SELECT ID FROM " + table)) {
      if (!rs.next()) {
        fail("Metadata extraction must preserve caller work");
      }
      assertEquals(42, rs.getInt(1));
    }
  }

  private static JdbcTable table(JdbcMetaData metadata, String schema, String name) {
    return metadata.getCatalogsList().stream().flatMap(c -> c.schemas.values().stream())
        .filter(
            s -> schema.equalsIgnoreCase(s.tableSchema) || schema.equalsIgnoreCase(s.tableCatalog))
        .map(s -> s.get(name)).filter(t -> t != null).findFirst()
        .orElseThrow(() -> new AssertionError("Missing table " + schema + "." + name));
  }

  private static Object invoke(Object target, Method method, Object[] args) throws Throwable {
    try {
      return method.invoke(target, args);
    } catch (InvocationTargetException ex) {
      throw ex.getCause();
    }
  }

  private static Connection measure(Connection conn, AtomicInteger calls) throws Exception {
    Connection[] wrapped = new Connection[1];
    DatabaseMetaData metadata =
        (DatabaseMetaData) Proxy.newProxyInstance(Db2MySqlMetaDataTest.class.getClassLoader(),
            new Class<?>[] {DatabaseMetaData.class}, (proxy, method, args) -> {
              String name = method.getName();
              if ("getConnection".equals(name)) {
                return wrapped[0];
              }
              if (List.of("getPrimaryKeys", "getImportedKeys").contains(name)) {
                if (JdbcUtils.DatabaseSpecific.getType(conn.getMetaData()
                    .getDatabaseProductName()) != JdbcUtils.DatabaseSpecific.DB2) {
                  fail("MySQL keys must be fetched in bulk, not per table: " + name);
                }
                calls.incrementAndGet();
              }
              if (List.of("getCatalogs", "getSchemas", "getTables", "getColumns").contains(name)) {
                calls.incrementAndGet();
              }
              return invoke(conn.getMetaData(), method, args);
            });
    wrapped[0] = (Connection) Proxy.newProxyInstance(Db2MySqlMetaDataTest.class.getClassLoader(),
        new Class<?>[] {Connection.class}, (proxy, method, args) -> {
          if ("getMetaData".equals(method.getName())) {
            return metadata;
          }
          if (List.of("prepareStatement", "createStatement").contains(method.getName())) {
            calls.incrementAndGet();
          }
          return invoke(conn, method, args);
        });
    return wrapped[0];
  }
}
