/**
 * Starlake.AI JSQLTranspiler is a SQL to DuckDB Transpiler.
 * Copyright (C) 2025 Starlake.AI (hayssam.saleh@starlake.ai)
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ai.starlake.transpiler.schema;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Savepoint;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.*;

/** Live vendor regressions with isolated fixtures and explicit cleanup (Oracle DDL commits). */
class OracleSqlServerMetaDataTest {
  @ParameterizedTest(name = "{0}, autoCommit={1}")
  @CsvSource({"oracle,true", "oracle,false", "mssql,true", "mssql,false"})
  void catalogKeysAndTransactionPreservation(String database, boolean autoCommit) throws Exception {
    try (Connection conn = LiveDatabaseProperties.connect(database)) {
      boolean oracle = "oracle".equals(database);
      String prefix = "JT"
          + UUID.randomUUID().toString().replace("-", "").substring(0, 12).toUpperCase(Locale.ROOT);
      String schema = oracle ? conn.getMetaData().getUserName().toUpperCase(Locale.ROOT) : prefix;
      List<String> created = new ArrayList<>();
      String parent = schema + "." + prefix + "_P";
      String child = schema + "." + prefix + "_C";
      String composite = schema + "." + prefix + "_F";
      String noKey = schema + "." + prefix + "_N";
      conn.setAutoCommit(true);
      boolean schemaCreated = false;
      try {
        if (!oracle) {
          execute(conn, "CREATE SCHEMA " + schema);
          schemaCreated = true;
        }
        create(conn, created, parent, "ID INT "
            + (oracle ? "GENERATED BY DEFAULT AS IDENTITY" : "IDENTITY(1,1)") + " PRIMARY KEY");
        create(conn, created, child, "A INT, B INT, P INT, LABEL VARCHAR(40) DEFAULT 'pending', "
            + (oracle ? "COMPUTED INT GENERATED ALWAYS AS (A+B) VIRTUAL" : "COMPUTED AS (A+B)")
            + ", PRIMARY KEY(A,B), FOREIGN KEY(P) REFERENCES " + parent + "(ID) ON DELETE CASCADE");
        create(conn, created, composite,
            "X INT, Y INT, FOREIGN KEY(X,Y) REFERENCES " + child + "(A,B)");
        create(conn, created, noKey, "ID INT");
        execute(conn, "CREATE INDEX " + prefix + "_IX ON " + child + "(P)");
        if (oracle) {
          execute(conn, "COMMENT ON TABLE " + child + " IS 'Live child fixture'");
          execute(conn, "COMMENT ON COLUMN " + child + ".LABEL IS 'Live label fixture'");
        } else {
          execute(conn,
              "EXEC sys.sp_addextendedproperty @name=N'MS_Description', "
                  + "@value=N'Live child fixture', @level0type=N'SCHEMA', @level0name=N'" + schema
                  + "', @level1type=N'TABLE', @level1name=N'" + prefix + "_C'");
          execute(conn,
              "EXEC sys.sp_addextendedproperty @name=N'MS_Description', "
                  + "@value=N'Live label fixture', @level0type=N'SCHEMA', @level0name=N'" + schema
                  + "', @level1type=N'TABLE', @level1name=N'" + prefix
                  + "_C', @level2type=N'COLUMN', @level2name=N'LABEL'");
        }
        conn.setAutoCommit(autoCommit);
        execute(conn, "INSERT INTO " + noKey + " VALUES (42)");
        Savepoint caller = autoCommit ? null : conn.setSavepoint();
        AtomicInteger calls = new AtomicInteger();
        Connection measured = measure(conn, calls);
        String currentCatalog = conn.getCatalog();
        String currentSchema = conn.getSchema();
        JdbcMetaData metadata = new JdbcMetaData(measured, List.of(schema.toLowerCase(Locale.ROOT)),
            JdbcMetaDataOptions.defaults());
        int initialCalls = calls.get();
        JdbcTable p = table(metadata, schema, prefix + "_P");
        JdbcTable c = table(metadata, schema, prefix + "_C");
        JdbcTable f = table(metadata, schema, prefix + "_F");
        assertEquals(List.of("ID"), p.primaryKey.getColumnNames());
        assertEquals("YES", p.columns.get("ID").isAutomaticIncrement);
        assertEquals(List.of("A", "B"), c.primaryKey.getColumnNames());
        assertEquals(1, c.foreignKeys.size());
        assertEquals(DatabaseMetaData.importedKeyCascade,
            c.foreignKeys.get(0).deleteRule.intValue());
        assertEquals(1, f.foreignKeys.size());
        assertArrayEquals(new String[] {"X", "A"}, f.foreignKeys.get(0).columns.get(0));
        assertArrayEquals(new String[] {"Y", "B"}, f.foreignKeys.get(0).columns.get(1));
        assertNull(table(metadata, schema, prefix + "_N").primaryKey);
        assertEquals("Live child fixture", c.remarks);
        assertEquals("Live label fixture", c.columns.get("LABEL").remarks);
        assertTrue(c.columns.get("LABEL").columnDefinition.contains("pending"));
        assertEquals("YES", c.columns.get("COMPUTED").isGeneratedColumn);
        assertEquals(4, c.columns.get("LABEL").ordinalPosition);
        for (JdbcTable t : List.of(p, c, f)) {
          assertFalse(t.columns.isEmpty());
          for (JdbcColumn column : t.columns.values()) {
            assertEquals(t.tableCatalog, column.tableCatalog);
            assertEquals(t.tableSchema, column.tableSchema);
          }
        }
        String json = JdbcJSONSerializer.toJson(metadata).toString();
        assertEquals(json, JdbcJSONSerializer
            .toJson(JdbcJSONSerializer.fromJson(new java.io.StringReader(json))).toString());
        JdbcMetaData indexed = new JdbcMetaData(conn, List.of(schema),
            JdbcMetaDataOptions.defaults().setIndices(true));
        assertTrue(table(indexed, schema, prefix + "_C").indices.values().stream()
            .anyMatch(index -> (prefix + "_IX").equalsIgnoreCase(index.indexName)));
        assertEquals(currentCatalog, conn.getCatalog());
        assertEquals(currentSchema, conn.getSchema());
        assertEquals(autoCommit, conn.getAutoCommit());
        if (!autoCommit) {
          conn.rollback(caller);
        }
        assertMarker(conn, noKey);
        // End the transaction before Oracle's committing DDL; test a fresh transaction afterward.
        if (!autoCommit) {
          conn.rollback();
        }
        conn.setAutoCommit(true);
        for (int i = 0; i < 20; i++) {
          create(conn, created, schema + "." + prefix + "_M" + i,
              "ID INT PRIMARY KEY, P INT REFERENCES " + parent + "(ID)");
        }
        conn.setAutoCommit(autoCommit);
        calls.set(0);
        JdbcMetaData large =
            new JdbcMetaData(measured, List.of(schema), JdbcMetaDataOptions.defaults());
        assertEquals(initialCalls, calls.get(), "Metadata query count must not grow with tables");
        for (int i = 0; i < 20; i++) {
          JdbcTable t = table(large, schema, prefix + "_M" + i);
          assertNotNull(t.primaryKey);
          assertEquals(1, t.foreignKeys.size());
        }
        assertTrue(
            new JdbcMetaData(conn, List.of(prefix + "_MISSING"), JdbcMetaDataOptions.defaults())
                .getCatalogsList().stream().flatMap(catalog -> catalog.schemas.values().stream())
                .allMatch(s -> s.tables.isEmpty()));
        System.out.println(database + " " + conn.getMetaData().getDatabaseProductVersion()
            + ", driver " + conn.getMetaData().getDriverVersion() + ": " + initialCalls
            + " metadata calls for both 4 and 24 fixture tables; autoCommit=" + autoCommit);
      } finally {
        if (!conn.getAutoCommit()) {
          conn.rollback();
          conn.setAutoCommit(true);
        }
        for (int i = created.size() - 1; i >= 0; i--) {
          execute(conn, "DROP TABLE " + created.get(i) + (oracle ? " PURGE" : ""));
        }
        if (schemaCreated) {
          execute(conn, "DROP SCHEMA " + schema);
        }
      }
    }
  }

  private static void create(Connection conn, List<String> created, String table, String fields)
      throws Exception {
    execute(conn, "CREATE TABLE " + table + "(" + fields + ")");
    created.add(table);
  }

  private static void execute(Connection conn, String sql) throws Exception {
    try (Statement statement = conn.createStatement()) {
      statement.execute(sql);
    }
  }

  private static void assertMarker(Connection conn, String table) throws Exception {
    try (Statement statement = conn.createStatement();
        ResultSet rs = statement.executeQuery("SELECT ID FROM " + table)) {
      if (!rs.next()) {
        fail("Metadata extraction must preserve caller work");
      }
      assertEquals(42, rs.getInt(1));
    }
  }

  private static JdbcTable table(JdbcMetaData metadata, String schema, String name) {
    return metadata.getCatalogsList().stream().map(c -> c.get(schema)).filter(s -> s != null)
        .map(s -> s.get(name)).filter(t -> t != null).findFirst()
        .orElseThrow(() -> new AssertionError("Missing table " + schema + "." + name));
  }

  private static Object invoke(Object target, Method method, Object[] args) throws Throwable {
    try {
      return method.invoke(target, args);
    } catch (InvocationTargetException ex) {
      throw ex.getCause();
    }
  }

  private static Connection measure(Connection conn, AtomicInteger calls) throws Exception {
    Connection[] wrapped = new Connection[1];
    DatabaseMetaData metadata = (DatabaseMetaData) Proxy.newProxyInstance(
        OracleSqlServerMetaDataTest.class.getClassLoader(), new Class<?>[] {DatabaseMetaData.class},
        (proxy, method, args) -> {
          String name = method.getName();
          if ("getConnection".equals(name)) {
            return wrapped[0];
          }
          if (List.of("getPrimaryKeys", "getImportedKeys").contains(name)) {
            fail("Vendor keys must be fetched in bulk, not per table: " + name);
          }
          if (List.of("getCatalogs", "getSchemas", "getTables", "getColumns").contains(name)) {
            calls.incrementAndGet();
          }
          return invoke(conn.getMetaData(), method, args);
        });
    wrapped[0] =
        (Connection) Proxy.newProxyInstance(OracleSqlServerMetaDataTest.class.getClassLoader(),
            new Class<?>[] {Connection.class}, (proxy, method, args) -> {
              if ("getMetaData".equals(method.getName())) {
                return metadata;
              }
              if (List.of("prepareStatement", "createStatement").contains(method.getName())) {
                calls.incrementAndGet();
              }
              return invoke(conn, method, args);
            });
    return wrapped[0];
  }
}
